# Generated by Django 5.0.6 on 2024-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_creator_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
