# Generated by Django 5.0.6 on 2024-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='creator_type',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('GAME_DEVELOPER', 'Game Developer'), ('CONTENT_CREATOR', 'Content Creator'), ('ARTIST', 'Artist'), ('VOICE_ACTOR', 'Voice Actor'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='creator',
            name='request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
