# Generated by Django 5.0.6 on 2024-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_creator_creator_type_creator_request_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=200),
        ),
    ]
