# Generated by Django 5.0.6 on 2024-07-18 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0006_alter_creator_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
